UPDATE ck_playerrank SET countryCode="al" WHERE country="Albania";
UPDATE ck_playerrank SET countryCode="dz" WHERE country="Algeria";
UPDATE ck_playerrank SET countryCode="au" WHERE country="Australia";
UPDATE ck_playerrank SET countryCode="at" WHERE country="Austria";
UPDATE ck_playerrank SET countryCode="be" WHERE country="Belgium";
UPDATE ck_playerrank SET countryCode="ba" WHERE country="Bosnia and Herzegovina";
UPDATE ck_playerrank SET countryCode="bg" WHERE country="Bulgaria";
UPDATE ck_playerrank SET countryCode="ca" WHERE country="Canada";
UPDATE ck_playerrank SET countryCode="hr" WHERE country="Croatia";
UPDATE ck_playerrank SET countryCode="cz" WHERE country="Czechia";
UPDATE ck_playerrank SET countryCode="dk" WHERE country="Denmark";
UPDATE ck_playerrank SET countryCode="fi" WHERE country="Finland";
UPDATE ck_playerrank SET countryCode="fr" WHERE country="France";
UPDATE ck_playerrank SET countryCode="de" WHERE country="Germany";
UPDATE ck_playerrank SET countryCode="gl" WHERE country="Greenland";
UPDATE ck_playerrank SET countryCode="hu" WHERE country="Hungary";
UPDATE ck_playerrank SET countryCode="is" WHERE country="Iceland";
UPDATE ck_playerrank SET countryCode="in" WHERE country="India";
UPDATE ck_playerrank SET countryCode="ie" WHERE country="Ireland";
UPDATE ck_playerrank SET countryCode="il" WHERE country="Israel";
UPDATE ck_playerrank SET countryCode="it" WHERE country="Italy";
UPDATE ck_playerrank SET countryCode="lu" WHERE country="Luxembourg";
UPDATE ck_playerrank SET countryCode="mt" WHERE country="Malta";
UPDATE ck_playerrank SET countryCode="np" WHERE country="Nepal";
UPDATE ck_playerrank SET countryCode="no" WHERE country="Norway";
UPDATE ck_playerrank SET countryCode="pk" WHERE country="Pakistan";
UPDATE ck_playerrank SET countryCode="pl" WHERE country="Poland";
UPDATE ck_playerrank SET countryCode="pt" WHERE country="Portugal";
UPDATE ck_playerrank SET countryCode="ro" WHERE country="Romania";
UPDATE ck_playerrank SET countryCode="ru" WHERE country="Russia";
UPDATE ck_playerrank SET countryCode="rs" WHERE country="Serbia";
UPDATE ck_playerrank SET countryCode="sk" WHERE country="Slovakia";
UPDATE ck_playerrank SET countryCode="si" WHERE country="Slovenia";
UPDATE ck_playerrank SET countryCode="es" WHERE country="Spain";
UPDATE ck_playerrank SET countryCode="se" WHERE country="Sweden";
UPDATE ck_playerrank SET countryCode="ch" WHERE country="Switzerland";
UPDATE ck_playerrank SET countryCode="nl" WHERE country="The Netherlands";
UPDATE ck_playerrank SET countryCode="gb" WHERE country="The United Kingdom";
UPDATE ck_playerrank SET countryCode="us" WHERE country="The United States";
UPDATE ck_playerrank SET countryCode="tr" WHERE country="Turkey";
